@startuml "Casos de uso"

:Usuário: as Usuario
(Listar alertas) as (listar)
(Adicionar alerta) as (adicionar)

note top of Usuario : Todos os usuários possuem o mesmo papel.

Usuario ---> (listar)
Usuario ---> (adicionar)

note "Todos os alertas possuem:\n- Horário\n- Descrição" as N2

(listar) .r. N2
(adicionar) .l. N2

@enduml
